baseURL = "http://example.org/"
languageCode = "en-us"
title = "Data Science Talks"
theme = "story"

[[menu.social]]
  name = "GitHub"
  title = "fab fa-github-square"
  url = "https://github.com/jfear/datascience_presentations"

[[menu.main]]
  name = "Talks"
  title = "Talks"
  url = "/talks/"

[[menu.main]]
  name = "Slides"
  title = "Slides"
  url = "/slides/"

[[menu.main]]
  name = "Archives"
  title = "Archives"
  url = "/archives/"

[params]
  author = "Justin Fear"
  classes = []
  custom_css = ["css/slides.css"]

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]

